/*
  Generated by Make DParser Version 1.30.6a201e22e57e77c297d3c43fdb245125ed3b7d64
  Available at http://dparser.sf.net
*/

#line 7 "../inst/tran.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_gram = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_gram = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_gram = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_gram = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_gram = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_gram = {2, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_8_gram = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_gram = {3, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_12_gram = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_gram = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_14_gram = {6, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_15_gram = {1, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_16_gram = {0, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_17_gram = {2, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_18_gram = {6, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_gram = {4, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_20_gram = {8, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_21_gram = {6, 13, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_22_gram = {3, 14, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_23_gram = {2, 15, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_24_gram = {2, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_25_gram = {0, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_26_gram = {2, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_27_gram = {2, 18, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_28_gram = {2, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_gram = {0, 19, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_30_gram = {2, 20, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_31_gram = {2, 21, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_32_gram = {2, 22, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_33_gram = {0, 22, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_34_gram = {2, 23, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_35_gram = {1, 24, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_37_gram = {2, 25, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_38_gram = {2, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_39_gram = {0, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_40_gram = {2, 27, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_41_gram = {1, 28, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_45_gram = {2, 29, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_46_gram = {2, 30, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_47_gram = {0, 30, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_48_gram = {2, 31, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_49_gram = {1, 32, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_51_gram = {2, 33, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_52_gram = {2, 34, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_53_gram = {0, 34, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_54_gram = {2, 35, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_55_gram = {1, 36, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_57_gram = {2, 37, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_58_gram = {1, 38, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_60_gram = {1, 39, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_61_gram = {0, 39, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_62_gram = {1, 40, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_64_gram = {3, 41, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_65_gram = {1, 42, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_70_gram = {3, 42, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_71_gram = {5, 43, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_72_gram = {2, 44, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_73_gram = {0, 44, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_74_gram = {2, 45, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_75_gram = {1, 46, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_78_gram = {1, 47, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_79_gram = {1, 48, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_80_gram = {1, 49, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_81_gram = {1, 50, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_82_gram = {1, 51, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_83_gram = {1, 52, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_84_gram = {2, 53, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_85_gram = {0, 53, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_86_gram = {1, 54, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_88_gram = {3, 55, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_gram = {56, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_gram = {57, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_gram = {58, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_gram = {59, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_gram = {60, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_gram = {61, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_gram = {62, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_gram = {63, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_gram = {64, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_gram = {65, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_gram = {66, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_gram = {67, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_gram = {68, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_gram = {69, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_gram = {70, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_gram = {71, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_16_gram = {72, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_17_gram = {73, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_18_gram = {74, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_19_gram = {75, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_20_gram = {76, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_21_gram = {77, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_22_gram = {78, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_23_gram = {79, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_24_gram = {80, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_25_gram = {81, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_26_gram = {82, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_27_gram = {83, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_28_gram = {84, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_29_gram = {85, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_30_gram = {86, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_31_gram = {87, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_32_gram = {88, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_33_gram = {89, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_34_gram = {90, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_35_gram = {91, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_36_gram = {92, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_37_gram = {93, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_38_gram = {94, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_39_gram = {95, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_40_gram = {96, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_41_gram = {97, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_42_gram = {98, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_43_gram = {99, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_44_gram = {100, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_45_gram = {101, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_46_gram = {102, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_47_gram = {103, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_48_gram = {104, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_49_gram = {105, 0, 0, 0, -3, 0, NULL};
D_Shift d_shift_50_gram = {106, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_51_gram = {107, 0, 0, 0, -4, 0, NULL};
D_Shift d_shift_52_gram = {108, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_53_gram = {109, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_54_gram = {110, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_55_gram = {111, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_gram[] = {0};
D_Shift * d_accepts_diff_0_1_gram[] = {&d_shift_50_gram,0};
D_Shift * d_accepts_diff_0_2_gram[] = {&d_shift_17_gram,0};
D_Shift * d_accepts_diff_0_3_gram[] = {&d_shift_6_gram,0};
D_Shift ** d_accepts_diff_0_gram[] = {
d_accepts_diff_0_0_gram,
d_accepts_diff_0_1_gram,
d_accepts_diff_0_2_gram,
d_accepts_diff_0_3_gram
};

unsigned char d_scanner_0_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 4, 3, 3, 3, 3, 5, 6, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_2_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_gram[] = {&d_shift_0_gram,NULL};

unsigned char d_scanner_0_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_2_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_2_gram[] = {&d_shift_50_gram,NULL};

unsigned char d_scanner_0_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_5_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 10, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_6_gram[] = {&d_shift_4_gram,NULL};

unsigned char d_scanner_0_7_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_8_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_8_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_8_gram[] = {&d_shift_6_gram,NULL};

unsigned char d_scanner_0_9_1_gram[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 12, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_10_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_11_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_11_1_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_11_gram[] = {&d_shift_17_gram,NULL};

D_Shift * d_shift_0_12_gram[] = {&d_shift_10_gram,NULL};

D_Shift * d_accepts_diff_4_0_gram[] = {0};
D_Shift ** d_accepts_diff_4_gram[] = {
d_accepts_diff_4_0_gram
};

unsigned char d_scanner_4_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_4_1_gram[] = {&d_shift_7_gram,NULL};

D_Shift * d_accepts_diff_14_0_gram[] = {0};
D_Shift ** d_accepts_diff_14_gram[] = {
d_accepts_diff_14_0_gram
};

D_Shift * d_accepts_diff_17_0_gram[] = {0};
D_Shift ** d_accepts_diff_17_gram[] = {
d_accepts_diff_17_0_gram
};

unsigned char d_scanner_17_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_17_1_gram[] = {&d_shift_13_gram,NULL};

D_Shift * d_accepts_diff_19_0_gram[] = {0};
D_Shift ** d_accepts_diff_19_gram[] = {
d_accepts_diff_19_0_gram
};

unsigned char d_scanner_19_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_19_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_19_1_gram[] = {&d_shift_52_gram,NULL};

D_Shift * d_shift_19_2_gram[] = {&d_shift_53_gram,NULL};

D_Shift * d_accepts_diff_21_0_gram[] = {0};
D_Shift ** d_accepts_diff_21_gram[] = {
d_accepts_diff_21_0_gram
};

D_Shift * d_shift_21_1_gram[] = {&d_shift_5_gram,NULL};

D_Shift * d_accepts_diff_22_0_gram[] = {0};
D_Shift ** d_accepts_diff_22_gram[] = {
d_accepts_diff_22_0_gram
};

unsigned char d_scanner_22_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_22_1_gram[] = {&d_shift_35_gram,NULL};

D_Shift * d_shift_22_2_gram[] = {&d_shift_36_gram,NULL};

D_Shift * d_accepts_diff_23_0_gram[] = {0};
D_Shift ** d_accepts_diff_23_gram[] = {
d_accepts_diff_23_0_gram
};

unsigned char d_scanner_23_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_23_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_31_0_gram[] = {0};
D_Shift ** d_accepts_diff_31_gram[] = {
d_accepts_diff_31_0_gram
};

unsigned char d_scanner_31_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_31_0_1_gram[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_31_0_gram[] = {&d_shift_54_gram,NULL};

D_Shift * d_accepts_diff_37_0_gram[] = {0};
D_Shift ** d_accepts_diff_37_gram[] = {
d_accepts_diff_37_0_gram
};

unsigned char d_scanner_37_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_37_1_gram[] = {&d_shift_8_gram,NULL};

D_Shift * d_accepts_diff_44_0_gram[] = {0};
D_Shift * d_accepts_diff_44_1_gram[] = {&d_shift_47_gram,0};
D_Shift * d_accepts_diff_44_2_gram[] = {&d_shift_17_gram,0};
D_Shift * d_accepts_diff_44_3_gram[] = {&d_shift_50_gram,0};
D_Shift ** d_accepts_diff_44_gram[] = {
d_accepts_diff_44_0_gram,
d_accepts_diff_44_1_gram,
d_accepts_diff_44_2_gram,
d_accepts_diff_44_3_gram
};

unsigned char d_scanner_44_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 
4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 7, 6, 6, 6, 6, 6, 8, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 
11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_44_3_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_44_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_44_3_gram[] = {&d_shift_47_gram,NULL};

unsigned char d_scanner_44_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_44_4_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_5_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_5_1_gram[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_6_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_44_6_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_7_1_gram[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 14, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_8_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_44_8_gram[] = {&d_shift_48_gram,NULL};

unsigned char d_scanner_44_9_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_11_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0, 17, 0, 0, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_12_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_13_1_gram[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 20, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_14_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 21, 0, 0, 
22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_16_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_44_17_gram[] = {&d_shift_49_gram,NULL};

unsigned char d_scanner_44_18_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_44_20_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_48_0_gram[] = {0};
D_Shift ** d_accepts_diff_48_gram[] = {
d_accepts_diff_48_0_gram
};

unsigned char d_scanner_48_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_48_1_gram[] = {&d_shift_19_gram,NULL};

D_Shift * d_accepts_diff_50_0_gram[] = {0};
D_Shift ** d_accepts_diff_50_gram[] = {
d_accepts_diff_50_0_gram
};

unsigned char d_scanner_50_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_50_1_gram[] = {&d_shift_55_gram,NULL};

D_Shift * d_accepts_diff_52_0_gram[] = {0};
D_Shift ** d_accepts_diff_52_gram[] = {
d_accepts_diff_52_0_gram
};

unsigned char d_scanner_52_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
};

unsigned char d_scanner_52_1_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
};

D_Shift * d_shift_52_2_gram[] = {&d_shift_27_gram,NULL};

D_Shift * d_accepts_diff_53_0_gram[] = {0};
D_Shift ** d_accepts_diff_53_gram[] = {
d_accepts_diff_53_0_gram
};

unsigned char d_scanner_53_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_53_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_53_2_gram[] = {&d_shift_28_gram,NULL};

D_Shift * d_accepts_diff_54_0_gram[] = {0};
D_Shift ** d_accepts_diff_54_gram[] = {
d_accepts_diff_54_0_gram
};

unsigned char d_scanner_54_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 
};

unsigned char d_scanner_54_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 
};

unsigned char d_scanner_54_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 
};

D_Shift * d_shift_54_3_gram[] = {&d_shift_29_gram,NULL};

D_Shift * d_shift_54_4_gram[] = {&d_shift_30_gram,NULL};

D_Shift * d_accepts_diff_55_0_gram[] = {0};
D_Shift * d_accepts_diff_55_1_gram[] = {&d_shift_31_gram,0};
D_Shift * d_accepts_diff_55_2_gram[] = {&d_shift_32_gram,0};
D_Shift ** d_accepts_diff_55_gram[] = {
d_accepts_diff_55_0_gram,
d_accepts_diff_55_1_gram,
d_accepts_diff_55_2_gram
};

unsigned char d_scanner_55_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 0, 
};

unsigned char d_accepts_diff_55_1_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
};

D_Shift * d_shift_55_1_gram[] = {&d_shift_31_gram,NULL};

unsigned char d_accepts_diff_55_2_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_55_2_gram[] = {&d_shift_32_gram,NULL};

D_Shift * d_shift_55_3_gram[] = {&d_shift_33_gram,NULL};

D_Shift * d_shift_55_4_gram[] = {&d_shift_34_gram,NULL};

D_Shift * d_accepts_diff_57_0_gram[] = {0};
D_Shift ** d_accepts_diff_57_gram[] = {
d_accepts_diff_57_0_gram
};

unsigned char d_scanner_57_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_57_1_gram[] = {&d_shift_37_gram,NULL};

D_Shift * d_shift_57_2_gram[] = {&d_shift_38_gram,NULL};

D_Shift * d_accepts_diff_68_0_gram[] = {0};
D_Shift ** d_accepts_diff_68_gram[] = {
d_accepts_diff_68_0_gram
};

unsigned char d_scanner_68_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_68_1_gram[] = {&d_shift_41_gram,NULL};

D_Shift * d_accepts_diff_78_0_gram[] = {0};
D_Shift ** d_accepts_diff_78_gram[] = {
d_accepts_diff_78_0_gram
};

unsigned char d_scanner_78_0_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_78_1_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_78_2_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_78_3_1_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_78_4_gram[] = {&d_shift_9_gram,NULL};

D_Shift * d_accepts_diff_127_0_gram[] = {0};
D_Shift ** d_accepts_diff_127_gram[] = {
d_accepts_diff_127_0_gram
};

unsigned char d_scanner_127_0_0_gram[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

SB_uint8 d_scanner_0_gram[13] = {
{NULL, {d_scanner_0_0_0_gram, d_scanner_0_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_3_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_4_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_5_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_6_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_0_7_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_8_gram, {d_scanner_0_2_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_0_2_0_gram, d_scanner_0_9_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_0_10_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_11_gram, {d_scanner_0_2_0_gram, d_scanner_0_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_12_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_0_gram[13] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_3_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_8_0_gram, d_accepts_diff_0_8_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_11_0_gram, d_accepts_diff_0_11_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_4_gram[2] = {
{NULL, {d_scanner_4_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_4_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_4_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_14_gram[2] = {
{NULL, {d_scanner_0_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_14_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_17_gram[2] = {
{NULL, {d_scanner_17_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_17_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_17_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_19_gram[3] = {
{NULL, {d_scanner_19_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_19_1_gram, {d_scanner_19_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_19_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_19_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_21_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_17_0_0_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_21_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_21_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_22_gram[3] = {
{NULL, {d_scanner_22_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_22_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_22_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_22_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_23_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_23_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_23_1_0_gram, d_scanner_23_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_23_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_31_gram[2] = {
{d_shift_31_0_gram, {d_scanner_31_0_0_gram, d_scanner_31_0_1_gram
 , d_scanner_31_0_1_gram, d_scanner_31_0_1_gram}},
{d_shift_31_0_gram, {d_scanner_31_0_0_gram, d_scanner_31_0_1_gram
 , d_scanner_31_0_1_gram, d_scanner_31_0_1_gram}}
};

SB_trans_uint8 d_transition_31_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_37_gram[2] = {
{NULL, {d_scanner_37_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_37_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_37_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_44_gram[23] = {
{NULL, {d_scanner_44_0_0_gram, d_scanner_44_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_4_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_3_gram, {d_scanner_44_3_0_gram, d_scanner_44_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_3_gram, {d_scanner_44_4_0_gram, d_scanner_44_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_44_5_0_gram, d_scanner_44_5_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_44_6_0_gram, d_scanner_44_5_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_44_5_0_gram, d_scanner_44_7_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_8_gram, {d_scanner_44_2_0_gram, d_scanner_44_8_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_8_gram, {d_scanner_44_9_0_gram, d_scanner_44_8_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_3_0_gram, d_scanner_44_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_11_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_44_12_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_2_gram, {d_scanner_44_5_0_gram, d_scanner_44_13_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_14_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_8_gram, {d_scanner_44_9_0_gram, d_scanner_44_8_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_16_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_17_gram, {d_scanner_44_16_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_44_18_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_11_gram, {d_scanner_44_5_0_gram, d_scanner_44_5_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_44_20_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_44_8_gram, {d_scanner_44_20_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_0_12_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_44_gram[23] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_44_3_0_gram, d_accepts_diff_44_3_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_44_4_0_gram, d_accepts_diff_44_3_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_44_6_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_11_0_gram, d_accepts_diff_0_11_1_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_48_gram[2] = {
{NULL, {d_scanner_48_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_48_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_48_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_50_gram[2] = {
{NULL, {d_scanner_50_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_50_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_50_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_52_gram[3] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_52_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_52_1_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_52_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_52_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_53_gram[3] = {
{NULL, {d_scanner_53_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_53_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_53_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_53_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_54_gram[5] = {
{NULL, {d_scanner_54_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_54_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_54_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_54_3_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_54_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_54_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_55_gram[5] = {
{NULL, {d_scanner_55_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_55_1_gram, {d_scanner_54_1_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_55_2_gram, {d_scanner_54_2_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_55_3_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_55_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_55_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_55_1_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_55_2_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_57_gram[3] = {
{NULL, {d_scanner_57_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_57_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_57_2_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_57_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_68_gram[2] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_68_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_68_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_68_gram[2] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_78_gram[5] = {
{NULL, {d_scanner_0_0_2_gram, d_scanner_78_0_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_78_1_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_78_2_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{NULL, {d_scanner_0_0_2_gram, d_scanner_78_3_1_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_78_4_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_78_gram[5] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

SB_uint8 d_scanner_127_gram[3] = {
{NULL, {d_scanner_127_0_0_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_37_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}},
{d_shift_48_1_gram, {d_scanner_0_0_2_gram, d_scanner_0_0_2_gram
 , d_scanner_0_0_2_gram, d_scanner_0_0_2_gram}}
};

SB_trans_uint8 d_transition_127_gram[3] = {
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}},
{{d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram
 , d_accepts_diff_0_0_0_gram, d_accepts_diff_0_0_0_gram}}
};

unsigned char d_goto_valid_0_gram[] = {
0xbe,0x54,0x0,0x0,0x0,0x0,0x4,0x51,0x4,0x2,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_1_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_1_gram[] = {&d_reduction_85_gram};
D_RightEpsilonHint d_right_epsilon_hints_1_gram[] = {{0, 19, &d_reduction_83_gram}};
D_Reduction * d_reductions_2_gram[] = {&d_reduction_8_gram};
unsigned char d_goto_valid_3_gram[] = {
0xfe,0x54,0x0,0x0,0x0,0x0,0x4,0x51,0x4,0x2,0x0,0x0,0x0,0x4};
D_Reduction * d_reductions_3_gram[] = {&d_reduction_13_gram};
unsigned char d_goto_valid_4_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_5_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_6_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_7_gram[] = {&d_reduction_81_gram};
unsigned char d_goto_valid_9_gram[] = {
0xb8,0x54,0x0,0x0,0x0,0x0,0x4,0x51,0x4,0x2,0x0,0x0,0x0,0x4};
D_Reduction * d_reductions_9_gram[] = {&d_reduction_1_gram};
D_Reduction * d_reductions_10_gram[] = {&d_reduction_3_gram};
D_Reduction * d_reductions_11_gram[] = {&d_reduction_4_gram};
D_Reduction * d_reductions_12_gram[] = {&d_reduction_8_gram};
D_Reduction * d_reductions_13_gram[] = {&d_reduction_8_gram};
unsigned char d_goto_valid_14_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_15_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_16_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_17_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_19_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0xc0,0x0,0x0,0x0,0x0,0x0,0x0,0x30};
D_Reduction * d_reductions_19_gram[] = {&d_reduction_83_gram};
D_Reduction * d_reductions_20_gram[] = {&d_reduction_12_gram};
unsigned char d_goto_valid_21_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_22_gram[] = {
0x0,0x80,0x24,0x22,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_22_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_23_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_24_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
D_Reduction * d_reductions_25_gram[] = {&d_reduction_2_gram};
D_Reduction * d_reductions_26_gram[] = {&d_reduction_5_gram};
D_Reduction * d_reductions_27_gram[] = {&d_reduction_5_gram};
D_Reduction * d_reductions_28_gram[] = {&d_reduction_5_gram};
unsigned char d_goto_valid_29_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_29_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_30_gram[] = {&d_reduction_86_gram};
unsigned char d_goto_valid_31_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x40};
D_Reduction * d_reductions_32_gram[] = {&d_reduction_84_gram};
D_Reduction * d_reductions_33_gram[] = {&d_reduction_86_gram};
D_Reduction * d_reductions_34_gram[] = {&d_reduction_11_gram};
D_Reduction * d_reductions_35_gram[] = {&d_reduction_62_gram};
D_Reduction * d_reductions_36_gram[] = {&d_reduction_62_gram};
unsigned char d_goto_valid_37_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_38_gram[] = {
0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_38_gram[] = {&d_reduction_25_gram};
D_RightEpsilonHint d_right_epsilon_hints_38_gram[] = {{0, 52, &d_reduction_23_gram}};
unsigned char d_goto_valid_39_gram[] = {
0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_39_gram[] = {&d_reduction_29_gram};
D_RightEpsilonHint d_right_epsilon_hints_39_gram[] = {{0, 53, &d_reduction_27_gram}};
unsigned char d_goto_valid_40_gram[] = {
0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_40_gram[] = {&d_reduction_33_gram};
D_RightEpsilonHint d_right_epsilon_hints_40_gram[] = {{0, 54, &d_reduction_31_gram}};
unsigned char d_goto_valid_41_gram[] = {
0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_41_gram[] = {&d_reduction_39_gram};
D_RightEpsilonHint d_right_epsilon_hints_41_gram[] = {{0, 55, &d_reduction_37_gram}};
unsigned char d_goto_valid_42_gram[] = {
0x0,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_42_gram[] = {&d_reduction_47_gram};
D_RightEpsilonHint d_right_epsilon_hints_42_gram[] = {{0, 56, &d_reduction_45_gram}};
unsigned char d_goto_valid_43_gram[] = {
0x0,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_43_gram[] = {&d_reduction_53_gram};
D_RightEpsilonHint d_right_epsilon_hints_43_gram[] = {{0, 57, &d_reduction_51_gram}};
unsigned char d_goto_valid_44_gram[] = {
0x0,0x28,0x0,0x0,0x40,0xce,0x7,0x80,0x4,0x2,0x0,0x0,0x80,0x7};
D_Reduction * d_reductions_45_gram[] = {&d_reduction_60_gram};
D_Reduction * d_reductions_46_gram[] = {&d_reduction_82_gram};
unsigned char d_goto_valid_47_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_48_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_49_gram[] = {&d_reduction_22_gram};
unsigned char d_goto_valid_50_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80};
unsigned char d_goto_valid_51_gram[] = {
0xb0,0x54,0x0,0x0,0x0,0x0,0x4,0x51,0x4,0x2,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_52_gram[] = {
0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0};
D_Reduction * d_reductions_52_gram[] = {&d_reduction_23_gram};
unsigned char d_goto_valid_53_gram[] = {
0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x0};
D_Reduction * d_reductions_53_gram[] = {&d_reduction_27_gram};
unsigned char d_goto_valid_54_gram[] = {
0x0,0x0,0x80,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x60,0x0,0x0,0x0};
D_Reduction * d_reductions_54_gram[] = {&d_reduction_31_gram};
unsigned char d_goto_valid_55_gram[] = {
0x0,0x0,0x0,0x18,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x7,0x0,0x0};
D_Reduction * d_reductions_55_gram[] = {&d_reduction_37_gram};
unsigned char d_goto_valid_56_gram[] = {
0x0,0x0,0x0,0x80,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_56_gram[] = {&d_reduction_45_gram};
unsigned char d_goto_valid_57_gram[] = {
0x0,0x0,0x0,0x0,0x18,0x0,0x0,0x0,0x0,0x0,0x0,0x60,0x0,0x0};
D_Reduction * d_reductions_57_gram[] = {&d_reduction_51_gram};
unsigned char d_goto_valid_58_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_58_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_59_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_60_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_61_gram[] = {&d_reduction_78_gram};
D_Reduction * d_reductions_62_gram[] = {&d_reduction_79_gram};
D_Reduction * d_reductions_63_gram[] = {&d_reduction_80_gram};
D_Reduction * d_reductions_64_gram[] = {&d_reduction_65_gram};
D_Reduction * d_reductions_65_gram[] = {&d_reduction_65_gram};
D_Reduction * d_reductions_66_gram[] = {&d_reduction_57_gram};
D_Reduction * d_reductions_67_gram[] = {&d_reduction_58_gram};
unsigned char d_goto_valid_68_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0};
D_Reduction * d_reductions_68_gram[] = {&d_reduction_58_gram};
D_Reduction * d_reductions_69_gram[] = {&d_reduction_65_gram};
D_Reduction * d_reductions_70_gram[] = {&d_reduction_65_gram};
D_Reduction * d_reductions_71_gram[] = {&d_reduction_75_gram};
D_Reduction * d_reductions_72_gram[] = {&d_reduction_75_gram};
D_Reduction * d_reductions_73_gram[] = {&d_reduction_75_gram};
unsigned char d_goto_valid_74_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_74_gram[] = {&d_reduction_65_gram};
unsigned char d_goto_valid_75_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_76_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
D_Reduction * d_reductions_77_gram[] = {&d_reduction_88_gram};
unsigned char d_goto_valid_78_gram[] = {
0x0,0x3,0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_78_gram[] = {&d_reduction_16_gram};
D_RightEpsilonHint d_right_epsilon_hints_78_gram[] = {{0, 109, &d_reduction_14_gram}};
unsigned char d_goto_valid_79_gram[] = {
0x0,0x0,0x24,0x22,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_79_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_80_gram[] = {&d_reduction_24_gram};
unsigned char d_goto_valid_81_gram[] = {
0x0,0x0,0x20,0x22,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_81_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_82_gram[] = {&d_reduction_28_gram};
D_Reduction * d_reductions_83_gram[] = {&d_reduction_35_gram};
D_Reduction * d_reductions_84_gram[] = {&d_reduction_35_gram};
D_Reduction * d_reductions_85_gram[] = {&d_reduction_32_gram};
unsigned char d_goto_valid_86_gram[] = {
0x0,0x0,0x0,0x22,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_86_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_87_gram[] = {&d_reduction_41_gram};
D_Reduction * d_reductions_88_gram[] = {&d_reduction_41_gram};
D_Reduction * d_reductions_89_gram[] = {&d_reduction_41_gram};
D_Reduction * d_reductions_90_gram[] = {&d_reduction_41_gram};
D_Reduction * d_reductions_91_gram[] = {&d_reduction_38_gram};
unsigned char d_goto_valid_92_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_92_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_93_gram[] = {&d_reduction_49_gram};
D_Reduction * d_reductions_94_gram[] = {&d_reduction_49_gram};
D_Reduction * d_reductions_95_gram[] = {&d_reduction_46_gram};
unsigned char d_goto_valid_96_gram[] = {
0x0,0x0,0x0,0x0,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_96_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_97_gram[] = {&d_reduction_55_gram};
D_Reduction * d_reductions_98_gram[] = {&d_reduction_55_gram};
D_Reduction * d_reductions_99_gram[] = {&d_reduction_52_gram};
unsigned char d_goto_valid_100_gram[] = {
0x0,0x0,0x0,0x0,0xa0,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_100_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_101_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_102_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_103_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_104_gram[] = {
0x0,0x28,0x0,0x0,0x0,0xcc,0x7,0x80,0x4,0x2,0x0,0x0,0x80,0x7};
unsigned char d_goto_valid_105_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_105_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_106_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_106_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_107_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_108_gram[] = {
0xb0,0x54,0x0,0x0,0x0,0x0,0x4,0x51,0x4,0x2,0x0,0x0,0x0,0x4};
D_Reduction * d_reductions_109_gram[] = {&d_reduction_14_gram};
D_Reduction * d_reductions_110_gram[] = {&d_reduction_15_gram};
D_Reduction * d_reductions_111_gram[] = {&d_reduction_26_gram};
D_Reduction * d_reductions_112_gram[] = {&d_reduction_30_gram};
D_Reduction * d_reductions_113_gram[] = {&d_reduction_34_gram};
D_Reduction * d_reductions_114_gram[] = {&d_reduction_40_gram};
D_Reduction * d_reductions_115_gram[] = {&d_reduction_48_gram};
D_Reduction * d_reductions_116_gram[] = {&d_reduction_54_gram};
D_Reduction * d_reductions_117_gram[] = {&d_reduction_70_gram};
unsigned char d_goto_valid_118_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_119_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_120_gram[] = {&d_reduction_64_gram};
unsigned char d_goto_valid_121_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_121_gram[] = {&d_reduction_73_gram};
D_Reduction * d_reductions_122_gram[] = {&d_reduction_18_gram};
unsigned char d_goto_valid_123_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_124_gram[] = {&d_reduction_17_gram};
D_Reduction * d_reductions_125_gram[] = {&d_reduction_19_gram};
unsigned char d_goto_valid_126_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x4};
unsigned char d_goto_valid_127_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x1,0x8,0x0,0x0,0x0,0x0};
unsigned char d_goto_valid_128_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_128_gram[] = {&d_reduction_61_gram};
unsigned char d_goto_valid_129_gram[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_130_gram[] = {&d_reduction_71_gram};
unsigned char d_goto_valid_131_gram[] = {
0x0,0x0,0x0,0x20,0xa2,0x1,0x0,0x0,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_131_gram[] = {&d_reduction_61_gram};
D_Reduction * d_reductions_132_gram[] = {&d_reduction_72_gram};
D_Reduction * d_reductions_133_gram[] = {&d_reduction_20_gram};
D_Reduction * d_reductions_134_gram[] = {&d_reduction_21_gram};
D_Reduction * d_reductions_135_gram[] = {&d_reduction_74_gram};
unsigned short d_gotos_gram[437] = {
9,10,11,12,13,23,14,19,20,15,24,16,25,17,21,10,
11,12,13,22,14,27,28,15,29,16,30,17,35,48,26,12,
13,51,14,49,52,15,53,16,54,17,33,34,55,56,57,58,
76,18,77,78,81,83,103,3,104,105,106,4,50,5,107,18,
43,6,86,87,44,3,45,46,7,4,118,5,124,18,126,6,
127,128,108,3,47,38,7,4,39,5,47,40,119,6,120,41,
31,32,129,42,7,135,0,43,65,8,66,44,133,45,46,92,
93,110,111,96,97,82,80,8,100,101,36,37,0,130,0,131,
84,85,0,67,0,8,68,69,70,47,132,71,72,73,74,75,
102,0,0,47,43,47,0,0,44,0,45,46,59,79,13,60,
14,36,37,15,0,16,61,17,0,0,109,88,89,90,91,94,
95,114,98,99,47,42,0,0,0,43,0,0,0,44,0,45,
46,0,0,0,62,63,64,8,0,112,0,18,40,0,36,37,
41,3,0,0,42,4,0,5,43,113,0,6,44,41,45,46,
0,42,7,0,0,43,115,0,0,44,43,45,46,0,44,0,
45,46,116,36,37,0,44,0,45,46,117,0,45,46,122,0,
0,0,43,8,0,0,44,0,45,46,0,0,123,0,0,65,
43,66,36,37,44,0,45,46,0,0,0,0,0,0,134,36,
37,0,43,0,36,37,44,0,45,46,0,0,36,37,121,70,
36,37,71,72,73,74,75,136,0,0,0,43,36,37,0,44,
0,45,46,59,0,0,60,0,0,0,36,37,0,61,125,13,
0,14,0,0,15,0,16,0,17,0,0,0,36,37,0,0,
0,0,0,0,0,0,0,0,0,0,0,62,63,64,8,0,
0,0,0,0,0,36,37,0,0,0,0,0,18,0,0,0,
0,0,3,0,0,0,4,0,5,0,0,0,6,0,0,0,
0,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,8};

D_ErrorRecoveryHint d_error_recovery_hints_0_gram[] = {
{0, 4, ";"},
{0, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_14_gram[] = {{1, 4, ";"}};
D_ErrorRecoveryHint d_error_recovery_hints_19_gram[] = {{0, 55, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_21_gram[] = {{2, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_26_gram[] = {{2, 4, ";"}};
D_ErrorRecoveryHint d_error_recovery_hints_31_gram[] = {{1, 55, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_34_gram[] = {{3, 5, "}"}};
D_ErrorRecoveryHint d_error_recovery_hints_44_gram[] = {{0, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_50_gram[] = {{2, 55, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_58_gram[] = {{1, 42, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_59_gram[] = {{1, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_60_gram[] = {{1, 13, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_74_gram[] = {{1, 43, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_77_gram[] = {{3, 55, "\n"}};
D_ErrorRecoveryHint d_error_recovery_hints_101_gram[] = {{2, 42, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_102_gram[] = {{2, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_103_gram[] = {{2, 13, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_105_gram[] = {{2, 43, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_117_gram[] = {{3, 42, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_118_gram[] = {{3, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_119_gram[] = {{3, 13, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_121_gram[] = {{3, 43, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_125_gram[] = {{4, 11, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_126_gram[] = {{4, 13, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_127_gram[] = {{4, 43, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_129_gram[] = {{5, 13, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_130_gram[] = {{5, 43, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_134_gram[] = {{6, 13, ")"}};

D_State d_states_gram[] = {
{d_goto_valid_0_gram, 1, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_1_gram, 45, {1, d_reductions_1_gram}, {1, d_right_epsilon_hints_1_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_3_gram, -13, {1, d_reductions_3_gram}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_4_gram, 58, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_5_gram, 53, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_6_gram, 51, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{NULL, -2147483647, {1, d_reductions_7_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_9_gram, -27, {1, d_reductions_9_gram}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{NULL, -2147483647, {1, d_reductions_10_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_11_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_12_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_13_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_14_gram, 35, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_14_gram}, 1, NULL, (void*)d_scanner_14_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_gram, d_accepts_diff_14_gram, -1},
{d_goto_valid_15_gram, 34, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_14_gram}, 1, NULL, (void*)d_scanner_14_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_gram, d_accepts_diff_14_gram, -1},
{d_goto_valid_16_gram, 32, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_14_gram}, 1, NULL, (void*)d_scanner_14_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_14_gram, d_accepts_diff_14_gram, -1},
{d_goto_valid_17_gram, 43, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_gram, d_accepts_diff_17_gram, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_19_gram, 12, {1, d_reductions_19_gram}, {0, NULL}, {1, d_error_recovery_hints_19_gram}, 1, NULL, (void*)d_scanner_19_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_19_gram, d_accepts_diff_19_gram, -1},
{NULL, -2147483647, {1, d_reductions_20_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_21_gram, 33, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_21_gram}, 1, NULL, (void*)d_scanner_21_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_21_gram, d_accepts_diff_21_gram, -1},
{d_goto_valid_22_gram, -70, {1, d_reductions_22_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_23_gram, 22, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{d_goto_valid_24_gram, 16, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{NULL, -2147483647, {1, d_reductions_25_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_26_gram}, {0, NULL}, {1, d_error_recovery_hints_26_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_27_gram}, {0, NULL}, {1, d_error_recovery_hints_26_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_gram}, {0, NULL}, {1, d_error_recovery_hints_26_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_29_gram, -31, {1, d_reductions_29_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_30_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_31_gram, 77, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_31_gram}, 1, NULL, (void*)d_scanner_31_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_gram, d_accepts_diff_31_gram, -1},
{NULL, -2147483647, {1, d_reductions_32_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_34_gram}, {0, NULL}, {1, d_error_recovery_hints_34_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_35_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_36_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_37_gram, 28, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{d_goto_valid_38_gram, -22, {1, d_reductions_38_gram}, {1, d_right_epsilon_hints_38_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_39_gram, -21, {1, d_reductions_39_gram}, {1, d_right_epsilon_hints_39_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_40_gram, -22, {1, d_reductions_40_gram}, {1, d_right_epsilon_hints_40_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_41_gram, -19, {1, d_reductions_41_gram}, {1, d_right_epsilon_hints_41_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_42_gram, -16, {1, d_reductions_42_gram}, {1, d_right_epsilon_hints_42_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_43_gram, -13, {1, d_reductions_43_gram}, {1, d_right_epsilon_hints_43_gram}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_44_gram, -93, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_44_gram}, 1, NULL, (void*)d_scanner_44_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_44_gram, d_accepts_diff_44_gram, -1},
{NULL, -2147483647, {1, d_reductions_45_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_46_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_47_gram, 16, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{d_goto_valid_48_gram, 25, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_48_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_48_gram, d_accepts_diff_48_gram, -1},
{NULL, -2147483647, {1, d_reductions_49_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_50_gram, 60, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_50_gram}, 1, NULL, (void*)d_scanner_50_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_50_gram, d_accepts_diff_50_gram, -1},
{d_goto_valid_51_gram, -153, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{d_goto_valid_52_gram, -35, {1, d_reductions_52_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_52_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_52_gram, d_accepts_diff_52_gram, -1},
{d_goto_valid_53_gram, -33, {1, d_reductions_53_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_53_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_53_gram, d_accepts_diff_53_gram, -1},
{d_goto_valid_54_gram, -43, {1, d_reductions_54_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_54_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_54_gram, d_accepts_diff_54_gram, -1},
{d_goto_valid_55_gram, -84, {1, d_reductions_55_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_55_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_55_gram, d_accepts_diff_55_gram, -1},
{d_goto_valid_56_gram, -84, {1, d_reductions_56_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_57_gram, -85, {1, d_reductions_57_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_57_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_57_gram, d_accepts_diff_57_gram, -1},
{d_goto_valid_58_gram, -115, {1, d_reductions_58_gram}, {0, NULL}, {1, d_error_recovery_hints_58_gram}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_59_gram, 9, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_59_gram}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_60_gram, 7, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_60_gram}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{NULL, -2147483647, {1, d_reductions_61_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_62_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_63_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_64_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_65_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_66_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_67_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_68_gram, 40, {1, d_reductions_68_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_68_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_68_gram, d_accepts_diff_68_gram, -1},
{NULL, -2147483647, {1, d_reductions_69_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_70_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_71_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_72_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_73_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_74_gram, 5, {1, d_reductions_74_gram}, {0, NULL}, {1, d_error_recovery_hints_74_gram}, 1, NULL, (void*)d_scanner_4_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_4_gram, d_accepts_diff_4_gram, -1},
{d_goto_valid_75_gram, 7, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_gram, d_accepts_diff_17_gram, -1},
{d_goto_valid_76_gram, -31, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{NULL, -2147483647, {1, d_reductions_77_gram}, {0, NULL}, {1, d_error_recovery_hints_77_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_78_gram, -105, {1, d_reductions_78_gram}, {1, d_right_epsilon_hints_78_gram}, {0, NULL}, 1, NULL, (void*)d_scanner_78_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_78_gram, d_accepts_diff_78_gram, -1},
{d_goto_valid_79_gram, -183, {1, d_reductions_79_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_80_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_81_gram, -196, {1, d_reductions_81_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_82_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_83_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_84_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_85_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_86_gram, -152, {1, d_reductions_86_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_87_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_88_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_89_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_90_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_91_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_92_gram, -201, {1, d_reductions_92_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_93_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_94_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_95_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_96_gram, -209, {1, d_reductions_96_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_97_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_98_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_99_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_100_gram, -213, {1, d_reductions_100_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_101_gram, -10, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_101_gram}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{d_goto_valid_102_gram, -41, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_102_gram}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{d_goto_valid_103_gram, -43, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_103_gram}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{d_goto_valid_104_gram, -260, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_44_gram}, 1, NULL, (void*)d_scanner_44_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_44_gram, d_accepts_diff_44_gram, -1},
{d_goto_valid_105_gram, -225, {1, d_reductions_105_gram}, {0, NULL}, {1, d_error_recovery_hints_105_gram}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_106_gram, -239, {1, d_reductions_106_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_107_gram, -12, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{d_goto_valid_108_gram, -330, {0, NULL}, {0, NULL}, {2, d_error_recovery_hints_0_gram}, 1, NULL, (void*)d_scanner_0_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_gram, d_accepts_diff_0_gram, -1},
{NULL, -2147483647, {1, d_reductions_109_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_110_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_111_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_112_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_113_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_114_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_115_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_116_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_117_gram}, {0, NULL}, {1, d_error_recovery_hints_117_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_118_gram, -14, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_118_gram}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{d_goto_valid_119_gram, -5, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_119_gram}, 1, NULL, (void*)d_scanner_48_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_48_gram, d_accepts_diff_48_gram, -1},
{NULL, -2147483647, {1, d_reductions_120_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_121_gram, -37, {1, d_reductions_121_gram}, {0, NULL}, {1, d_error_recovery_hints_121_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_122_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_123_gram, -29, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_gram, d_accepts_diff_17_gram, -1},
{NULL, -2147483647, {1, d_reductions_124_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_125_gram}, {0, NULL}, {1, d_error_recovery_hints_125_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_126_gram, -74, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_126_gram}, 1, NULL, (void*)d_scanner_23_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_gram, d_accepts_diff_23_gram, -1},
{d_goto_valid_127_gram, -63, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_127_gram}, 1, NULL, (void*)d_scanner_127_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_127_gram, d_accepts_diff_127_gram, -1},
{d_goto_valid_128_gram, -257, {1, d_reductions_128_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{d_goto_valid_129_gram, -37, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_129_gram}, 1, NULL, (void*)d_scanner_37_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_37_gram, d_accepts_diff_37_gram, -1},
{NULL, -2147483647, {1, d_reductions_130_gram}, {0, NULL}, {1, d_error_recovery_hints_130_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_131_gram, -282, {1, d_reductions_131_gram}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_22_gram, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_22_gram, d_accepts_diff_22_gram, -1},
{NULL, -2147483647, {1, d_reductions_132_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_133_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_134_gram}, {0, NULL}, {1, d_error_recovery_hints_134_gram}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_135_gram}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_gram[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_NTERM, "compound_statement", 18, -1},
{D_SYMBOL_INTERNAL, "compound_statement__6", 21, -1},
{D_SYMBOL_NTERM, "selection_statement", 19, -1},
{D_SYMBOL_INTERNAL, "selection_statement__9", 22, -1},
{D_SYMBOL_EBNF, "selection_statement__8", 22, -1},
{D_SYMBOL_NTERM, "derivative", 10, -1},
{D_SYMBOL_NTERM, "der_rhs", 7, -1},
{D_SYMBOL_NTERM, "jac", 3, -1},
{D_SYMBOL_NTERM, "jac_rhs", 7, -1},
{D_SYMBOL_NTERM, "assignment", 10, -1},
{D_SYMBOL_NTERM, "logical_or_expression", 21, -1},
{D_SYMBOL_INTERNAL, "logical_or_expression__17", 25, -1},
{D_SYMBOL_EBNF, "logical_or_expression__16", 25, -1},
{D_SYMBOL_NTERM, "logical_and_expression", 22, -1},
{D_SYMBOL_INTERNAL, "logical_and_expression__20", 26, -1},
{D_SYMBOL_EBNF, "logical_and_expression__19", 26, -1},
{D_SYMBOL_NTERM, "equality_expression", 19, -1},
{D_SYMBOL_INTERNAL, "equality_expression__24", 23, -1},
{D_SYMBOL_EBNF, "equality_expression__22", 23, -1},
{D_SYMBOL_EBNF, "equality_expression__22__23", 27, -1},
{D_SYMBOL_NTERM, "relational_expression", 21, -1},
{D_SYMBOL_INTERNAL, "relational_expression__28", 25, -1},
{D_SYMBOL_EBNF, "relational_expression__26", 25, -1},
{D_SYMBOL_EBNF, "relational_expression__26__27", 29, -1},
{D_SYMBOL_NTERM, "additive_expression", 19, -1},
{D_SYMBOL_INTERNAL, "additive_expression__32", 23, -1},
{D_SYMBOL_EBNF, "additive_expression__30", 23, -1},
{D_SYMBOL_EBNF, "additive_expression__30__31", 27, -1},
{D_SYMBOL_NTERM, "multiplicative_expression", 25, -1},
{D_SYMBOL_INTERNAL, "multiplicative_expression__36", 29, -1},
{D_SYMBOL_EBNF, "multiplicative_expression__34", 29, -1},
{D_SYMBOL_EBNF, "multiplicative_expression__34__35", 33, -1},
{D_SYMBOL_NTERM, "unary_expression", 16, -1},
{D_SYMBOL_EBNF, "unary_expression__40", 20, -1},
{D_SYMBOL_INTERNAL, "unary_expression__39", 20, -1},
{D_SYMBOL_EBNF, "unary_expression__38", 20, -1},
{D_SYMBOL_NTERM, "power_expression", 16, -1},
{D_SYMBOL_NTERM, "primary_expression", 18, -1},
{D_SYMBOL_NTERM, "function", 8, -1},
{D_SYMBOL_INTERNAL, "function__45", 12, -1},
{D_SYMBOL_EBNF, "function__44", 12, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_NTERM, "identifier", 10, -1},
{D_SYMBOL_NTERM, "identifier_no_output", 20, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__54", 14, -1},
{D_SYMBOL_EBNF, "whitespace__53", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, ";", 1},
{D_SYMBOL_STRING, "{", 1},
{D_SYMBOL_STRING, "}", 1},
{D_SYMBOL_STRING, "if", 2},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "else", 4},
{D_SYMBOL_STRING, "d/dt", 4},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "=", 1},
{D_SYMBOL_STRING, "d/dt", 4},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "jac", 3},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ",", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "=", 1},
{D_SYMBOL_STRING, "jac", 3},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ",", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "=", 1},
{D_SYMBOL_STRING, "||", 2},
{D_SYMBOL_STRING, "&&", 2},
{D_SYMBOL_STRING, "!=", 2},
{D_SYMBOL_STRING, "==", 2},
{D_SYMBOL_STRING, "<", 1},
{D_SYMBOL_STRING, ">", 1},
{D_SYMBOL_STRING, "<=", 2},
{D_SYMBOL_STRING, ">=", 2},
{D_SYMBOL_STRING, "+", 1},
{D_SYMBOL_STRING, "-", 1},
{D_SYMBOL_STRING, "*", 1},
{D_SYMBOL_STRING, "/", 1},
{D_SYMBOL_STRING, "+", 1},
{D_SYMBOL_STRING, "-", 1},
{D_SYMBOL_STRING, "^", 1},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_STRING, "(", 1},
{D_SYMBOL_STRING, ",", 1},
{D_SYMBOL_STRING, ")", 1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29},
{D_SYMBOL_REGEX, "[a-zA-Z_][a-zA-Z0-9_]*", 22},
{D_SYMBOL_REGEX, "[a-zA-Z_][a-zA-Z0-9_]*", 22},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13},
{D_SYMBOL_STRING, "#", 1},
{D_SYMBOL_REGEX, "[^\\n]*", 7},
{D_SYMBOL_STRING, "\\n", 3},
};

D_ParserTables parser_tables_gram = {
136, d_states_gram, d_gotos_gram, 1, 112, d_symbols_gram, NULL, 0, NULL, 0};
