---
title: "RxODE Benchmarking"
author: "Matthew L. Fidler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to RxODE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Setup the RxODE models and event table for comparison

```{r}
library(RxODE)

ver <- packageVersion("RxODE")

ver.no <- ver$minor

et <- eventTable();
et$add.dosing(dose=3, nbr.doses=6, dosing.interval=8)
et$add.sampling(seq(0, 48, length.out=200))

if (ver.no > 5){
    solve.1c <- RxODE({
        C2 = linCmt(CL, V);
    })
    solve.1c.ka <- RxODE({
        C2 = linCmt(V, CL, KA);
    })
    solve.2c <- RxODE({
        C2=linCmt(V, CL, V2, Q);
    })
    solve.2c.ka <- RxODE({
        C2=linCmt(V, CL, V2, Q, KA);
    })
    solve.3c <- RxODE({
        ## double solvedC(double t, int parameterization, int cmt, unsigned int col, double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8);
        C2=linCmt(V, CL, V2, Q, Q2, V3);
    })
    solve.3c.ka <- RxODE({
        ## double solvedC(double t, int parameterization, int cmt, unsigned int col, double p1, double p2, double p3, double p4, double p5, double p6, double p7, double p8);
        C2=linCmt(V, CL, V2, Q, Q2, V3, KA);
    })
}

ode.1c <- RxODE("
C2 = center/V;
d/dt(center) = - CL*C2;
","ode1c")



ode.1c.ka <- RxODE("
    C2 = center/V;
    d/dt(depot) = -KA * depot;
    d/dt(center) = KA * depot - CL*C2;
","ode1cka")

ode.2c <- RxODE("
    C2 = centr/V;
    C3 = peri/V2;
    d/dt(centr) = - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  = Q*C2 - Q*C3;
", "ode2c")


ode.2c.ka <- RxODE("
   C2 = centr/V;
   C3 = peri/V2;
   d/dt(depot) =-KA*depot;
   d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
   d/dt(peri)  =                    Q*C2 - Q*C3;
","ode2cka")

ode.3c <- RxODE("
     C2 = centr/V;
     C3 = peri/V2;
     C4 = peri2 / V3;
     d/dt(centr) = - CL*C2 - Q*C2 + Q*C3  - Q2*C2 + Q2*C4;
     d/dt(peri)  = Q*C2 - Q*C3;
     d/dt(peri2) = Q2 * C2 - Q2 * C4;
 ","ode3c")
 
 ode.3c.ka <- RxODE("
     C2 = centr/V;
     C3 = peri/V2;
     C4 = peri2 / V3;
	 d/dt(depot) =-KA*depot;
     d/dt(centr) = KA*depot- CL*C2 - Q*C2 + Q*C3  - Q2*C2 + Q2*C4;
     d/dt(peri)  = Q*C2 - Q*C3;
     d/dt(peri2) = Q2 * C2 - Q2 * C4;
 ","ode3cka")

```


## Benchmarking the Models
These benchmark the single solve
```{r}

library(microbenchmark)

if (ver.no > 5){
    res.rxSolve <- microbenchmark(solved.1c=rxSolve(solve.1c, params=c(V=20, CL=25), events=et),
                                  solved.1c.ka=rxSolve(solve.1c.ka, params=c(V=20, CL=25, KA=2), events=et),
                                  solved.2c=rxSolve(solve.2c, params=c(V=20, CL=25, V2=297, Q=10), events=et),
                                  solved.2c.ka=rxSolve(solve.2c.ka, params=c(V=20, CL=25, V2=297, Q=10, KA=2), events=et),
                                  solved.3c=rxSolve(solve.3c, params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400), events=et),
                                  solved.3c.ka=rxSolve(solve.3c.ka, params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400, KA=2), events=et) 
                                  )
}

if (ver.no > 7){
    res7.rxSolve <- microbenchmark(ode.1c.liblsoda=rxSolve(ode.1c, params=c(V=20, CL=25), events=et, method="liblsoda"),
                                   ode.1c.ka.liblsoda=rxSolve(ode.1c.ka, params=c(V=20, CL=25, KA=2), events=et, method="liblsoda"),
                                   ode.2c.liblsoda=rxSolve(ode.2c, params=c(V=20, CL=25, V2=297, Q=10), events=et, method="liblsoda"),
                                   ode.2c.ka.liblsoda=rxSolve(ode.2c.ka, params=c(V=20, CL=25, V2=297, Q=10, KA=2), events=et, method="liblsoda"),
                                   ode.3c.liblsoda=rxSolve(ode.3c, params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400), events=et, method="liblsoda"),
                                   ode.3c.ka.liblsoda=rxSolve(ode.3c.ka, params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400, KA=2), events=et, method="liblsoda"),
                                   )
}

res.run <- microbenchmark(
    ode.1c.lsoda=ode.1c$run(params=c(V=20, CL=25), events=et, stiff=TRUE),
    ode.1c.dop=ode.1c$run(params=c(V=20, CL=25), events=et, stiff=FALSE),
    ode.1c.ka.lsoda=ode.1c.ka$run(params=c(V=20, CL=25, KA=2), events=et, stiff=TRUE),
    ode.1c.ka.dop=ode.1c.ka$run(params=c(V=20, CL=25, KA=2), events=et, stiff=FALSE),
    ode.2c.lsoda=ode.2c$run(params=c(V=20, CL=25, V2=297, Q=10), events=et, stiff=TRUE),
    ode.2c.dop=ode.2c$run(params=c(V=20, CL=25, V2=297, Q=10), events=et, stiff=FALSE),
    ode.2c.ka.lsoda=ode.2c.ka$run(params=c(V=20, CL=25, V2=297, Q=10, KA=2), events=et, stiff=TRUE),
    ode.2c.ka.dop=ode.2c.ka$run(params=c(V=20, CL=25, V2=297, Q=10, KA=2), events=et, stiff=FALSE),
    ode.3c.lsoda=ode.3c$run(params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400), events=et, stiff=TRUE),
    ode.3c.dop=ode.3c$run(params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400), events=et, stiff=FALSE),
    ode.3c.ka.lsoda=ode.3c.ka$run(params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400, KA=2), events=et, stiff=TRUE),
    ode.3c.ka.dop=ode.3c.ka$run(params=c(V=20, CL=25, V2=297, Q=10, Q2=7, V3=400, KA=2), events=et, stiff=FALSE))

```

0.5.3 solve speeds

Unit: microseconds
            expr     min       lq     mean   median        uq      max neval
    ode.1c.lsoda 347.627 390.9135 551.1030 438.6620  715.3360 1004.950   100
      ode.1c.dop 511.401 595.7410 834.2383 866.6135 1006.0660 1671.645   100
 ode.1c.ka.lsoda 360.568 409.4325 612.0649 527.9115  770.4475 1848.805   100
   ode.1c.ka.dop 517.201 601.9885 940.1150 907.4450 1092.6385 4294.690   100
    ode.2c.lsoda 380.203 425.2745 606.0941 541.9680  791.6435  965.234   100
      ode.2c.dop 525.680 578.7840 865.9800 709.3110 1047.5675 3695.825   100
 ode.2c.ka.lsoda 402.515 464.5445 709.5700 730.5075  846.5330 2250.428   100
   ode.2c.ka.dop 535.051 618.2770 929.9272 995.1330 1110.2645 3730.632   100
    ode.3c.lsoda 419.919 505.3765 769.5949 781.1570  918.6020 2007.223   100
      ode.3c.dop 553.348 627.6475 920.1455 799.4530 1068.7640 4702.114   100
 ode.3c.ka.lsoda 418.135 479.9395 677.4090 539.9600  871.2995 1700.651   100
   ode.3c.ka.dop 576.998 662.4550 953.7390 911.4620 1166.7150 3182.640   100

0.6.3 solve speeds
