rxPermissive({
    context("rxIs")
    library(dplyr)
    load(devtools::package_file("tests/testthat/test-data-setup.Rdata"))
    dat <- as.tbl(dat);
    test_that("rxIs tests", {
        expect_true(rxIs(dat, "data.frame"))
        expect_true(rxIs(dat, "tbl"))
        expect_true(rxIs(dat, "tbl_df"))
        expect_true(rxIs(dat, "event.data.frame"))
        dat2 <- dat %>% mutate(amt=AMT, evid=EVID, time=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_true(rxIs(dat2, "event.data.frame"))
        dat3 <- dat %>% mutate(Amt=AMT, Evid=EVID, Time=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_true(rxIs(dat3, "event.data.frame"))
        dat4 <- dat %>% mutate(AMt=AMT, EVid=EVID, TIme=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_false(rxIs(dat4, "event.data.frame"))
        dat <- as.data.frame(dat)
        expect_true(rxIs(dat, "data.frame"))
        expect_false(rxIs(dat, "tbl"))
        expect_false(rxIs(dat, "tbl_df"))
        expect_true(rxIs(dat, "event.data.frame"))
        expect_false(rxIs(as.matrix(dat), "event.data.frame"))
        expect_true(rxIs(as.matrix(dat), "event.matrix"))
        dat2 <- dat %>% mutate(amt=AMT, evid=EVID, time=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_true(rxIs(dat2, "event.data.frame"))
        expect_true(rxIs(as.matrix(dat2), "event.matrix"))
        dat3 <- dat %>% mutate(Amt=AMT, Evid=EVID, Time=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_true(rxIs(dat3, "event.data.frame"))
        dat4 <- dat %>% mutate(AMt=AMT, EVid=EVID, TIme=TIME) %>% select(-AMT, -EVID, -TIME)
        expect_false(rxIs(as.matrix(dat4), "event.matrix"))
        expect_false(rxIs(dat4, "event.data.frame"))
        expect_false(rxIs(as.matrix(dat4), "event.matrix"))
        a <- numeric()
        expect_true(rxIs(a, "numeric"))
        a <- numeric(1)
        expect_true(rxIs(a, "numeric"))
        a <- matrix(a)
        expect_true(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- integer()
        expect_true(rxIs(a, "integer"))
        a <- integer(1)
        expect_true(rxIs(a, "integer"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_true(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- logical()
        expect_true(rxIs(a, "logical"))
        a <- logical(1)
        expect_true(rxIs(a, "logical"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_true(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- character()
        expect_true(rxIs(a, "character"))
        a <- character(1)
        expect_true(rxIs(a, "character"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_true(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        expect_true(rxIs(list(a="b"), "list"))
        expect_true(rxIs(list(), "list"))
        expect_true(rxIs(list("b"), "list"))
    })
}, cran=TRUE)
