rxPermissive({
    context("rxIs")
    library(dplyr)
    load(devtools::package_file("tests/testthat/test-data-setup.Rdata"))
    dat <- as.tbl(dat);
    test_that("rxIs tests", {
        expect_true(rxIs(dat, "data.frame"))
        expect_true(rxIs(dat, "tbl"))
        expect_true(rxIs(dat, "tbl_df"))
        dat <- as.data.frame(dat)
        expect_true(rxIs(dat, "data.frame"))
        expect_false(rxIs(dat, "tbl"))
        expect_false(rxIs(dat, "tbl_df"))
        a <- numeric()
        expect_true(rxIs(a, "numeric"))
        a <- numeric(1)
        expect_true(rxIs(a, "numeric"))
        a <- matrix(a)
        expect_true(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- integer()
        expect_true(rxIs(a, "integer"))
        a <- integer(1)
        expect_true(rxIs(a, "integer"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_true(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- logical()
        expect_true(rxIs(a, "logical"))
        a <- logical(1)
        expect_true(rxIs(a, "logical"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_true(rxIs(a, "logical.matrix"))
        expect_false(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
        a <- character()
        expect_true(rxIs(a, "character"))
        a <- character(1)
        expect_true(rxIs(a, "character"))
        a <- matrix(a)
        expect_false(rxIs(a, "numeric.matrix"))
        expect_false(rxIs(a, "integer.matrix"))
        expect_false(rxIs(a, "logical.matrix"))
        expect_true(rxIs(a, "character.matrix"))
        expect_true(rxIs(a, "matrix"))
    })
}, cran=TRUE)
