#pragma once
#ifndef __RxODE_control_H__
#define __RxODE_control_H__
#define Rxc_scale 0
#define Rxc_method 1
#define Rxc_transitAbs 2
#define Rxc_atol 3
#define Rxc_rtol 4
#define Rxc_maxsteps 5
#define Rxc_hmin 6
#define Rxc_hmax 7
#define Rxc_hini 8
#define Rxc_maxordn 9
#define Rxc_maxords 10
#define Rxc_covsInterpolation 11
#define Rxc_cores 12
#define Rxc_addCov 13
#define Rxc_matrix 14
#define Rxc_sigma 15
#define Rxc_sigmaDf 16
#define Rxc_nCoresRV 17
#define Rxc_sigmaIsChol 18
#define Rxc_sigmaSeparation 19
#define Rxc_sigmaXform 20
#define Rxc_nDisplayProgress 21
#define Rxc_amountUnits 22
#define Rxc_timeUnits 23
#define Rxc_theta 24
#define Rxc_eta 25
#define Rxc_addDosing 26
#define Rxc_stateTrim 27
#define Rxc_updateObject 28
#define Rxc_omega 29
#define Rxc_omegaDf 30
#define Rxc_omegaIsChol 31
#define Rxc_omegaSeparation 32
#define Rxc_omegaXform 33
#define Rxc_nSub 34
#define Rxc_thetaMat 35
#define Rxc_thetaDf 36
#define Rxc_thetaIsChol 37
#define Rxc_nStud 38
#define Rxc_dfSub 39
#define Rxc_dfObs 40
#define Rxc_seed 41
#define Rxc_nsim 42
#define Rxc_minSS 43
#define Rxc_maxSS 44
#define Rxc_strictSS 45
#define Rxc_infSSstep 46
#define Rxc_istateReset 47
#define Rxc_subsetNonmem 48
#define Rxc_linLog 49
#define Rxc_advanLinCmt 50
#define Rxc_hmaxSd 51
#define Rxc_maxAtolRtolFactor 52
#define Rxc_from 53
#define Rxc_to 54
#define Rxc_by 55
#define Rxc_length_out 56
#define Rxc_iCov 57
#define Rxc_keep 58
#define Rxc_keepF 59
#define Rxc_keepI 60
#define Rxc_drop 61
#define Rxc_warnDrop 62
#define Rxc_omegaLower 63
#define Rxc_omegaUpper 64
#define Rxc_sigmaLower 65
#define Rxc_sigmaUpper 66
#define Rxc_thetaLower 67
#define Rxc_thetaUpper 68
#define Rxc_indLinPhiM 69
#define Rxc_indLinPhiTol 70
#define Rxc_indLinMatExpType 71
#define Rxc_indLinMatExpOrder 72
#define Rxc_idFactor 73
#define Rxc_mxhnil 74
#define Rxc_hmxi 75
#define Rxc_warnIdSort 76
#define Rxc_ssAtol 77
#define Rxc_ssRtol 78
#define Rxc_safeZero 79
#define Rxc_cacheEvent 80
#define Rxc_mvnfast 81
#define Rxc_sumType 82
#define Rxc_prodType 83
#define RxMv_params 0
#define RxMv_lhs 1
#define RxMv_state 2
#define RxMv_trans 3
#define RxMv_model 4
#define RxMv_ini 5
#define RxMv_podo 6
#define RxMv_dfdy 7
#define RxMv_sens 8
#define RxMv_state_ignore 9
#define RxMv_version 10
#define RxMv_normal_state 11
#define RxMv_needSort 12
#define RxMv_nMtime 13
#define RxMv_extraCmt 14
#define RxMv_stateExtra 15
#define RxMv_dvid 16
#define RxMv_indLin 17
#define RxMv_flags 18
#define RxMv_timeId 19
#define RxMv_md5 20
#define RxMvFlag_ncmt 0
#define RxMvFlag_ka 1
#define RxMvFlag_linB 2
#define RxMvFlag_maxeta 3
#define RxMvFlag_maxtheta 4
#define RxMvFlag_hasCmt 5
#endif // __RxODE_control_H__
