# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rxInner <- function(etanews, rho) {
    invisible(.Call('RxODE_rxInner', PACKAGE = 'RxODE', etanews, rho))
}

rxHessian <- function(rho) {
    invisible(.Call('RxODE_rxHessian', PACKAGE = 'RxODE', rho))
}

RxODE_focei_eta_lik <- function(sexp_eta, sexp_rho) {
    .Call('RxODE_RxODE_focei_eta_lik', PACKAGE = 'RxODE', sexp_eta, sexp_rho)
}

RxODE_focei_eta_lp <- function(sexp_eta, sexp_rho) {
    .Call('RxODE_RxODE_focei_eta_lp', PACKAGE = 'RxODE', sexp_eta, sexp_rho)
}

RxODE_focei_eta <- function(fstr) {
    .Call('RxODE_RxODE_focei_eta', PACKAGE = 'RxODE', fstr)
}

RxODE_focei_finalize_llik <- function(rho) {
    .Call('RxODE_RxODE_focei_finalize_llik', PACKAGE = 'RxODE', rho)
}

RxODE_finalize_log_det_OMGAinv_5 <- function(rho) {
    .Call('RxODE_RxODE_finalize_log_det_OMGAinv_5', PACKAGE = 'RxODE', rho)
}

RxODE_finalize_focei_omega <- function(rho) {
    invisible(.Call('RxODE_RxODE_finalize_focei_omega', PACKAGE = 'RxODE', rho))
}

#' Calculate d(eta)/d(omega)
#'
#' @param eta the eta to caluclate the differential for.
#'
#' @param rho environment where omegaInv.dOmega.omegaInv and tr.omegaInv.dOmega.0.5
#' are calculated.  This is done with the rxSymInv function.
#'
#' @return Nothing.  Add omega.28 and omega.47 to the environment rho.
#' 
#' @keywords internal
#' @export
rxDetaDomega <- function(rho) {
    invisible(.Call('RxODE_rxDetaDomega', PACKAGE = 'RxODE', rho))
}

rxOuter_ <- function(rho) {
    invisible(.Call('RxODE_rxOuter_', PACKAGE = 'RxODE', rho))
}

rxDetaDtheta <- function(rho) {
    invisible(.Call('RxODE_rxDetaDtheta', PACKAGE = 'RxODE', rho))
}

rxOuter <- function(rho) {
    .Call('RxODE_rxOuter', PACKAGE = 'RxODE', rho)
}

#' Update ETAs based on d(eta)/d(theta)
#'
#' This updates the ETA initial estimates based on the knowledge of d(eta)/d(theta)
#'
#' @param DnDhS This is the d(eta)/d(theta) list where there is a
#'   d(eta)/d(theta) matrix for each subject
#'
#' @param DhS This is the change in theta observed between steps.
#'
#' @param initS This is the ETA intiail condition matrix
#'
#' @param acceptNS Acceptance criteria for the new eta.  |eta| < acceptNS for the new eta
#'   to be accepted.
#'
#' @keywords internal
#'
#' @export
rxUpdateEtas <- function(DnDhS, DhS, initS, acceptNS) {
    .Call('RxODE_rxUpdateEtas', PACKAGE = 'RxODE', DnDhS, DhS, initS, acceptNS)
}

