on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - name: Install packages from cran (source)
        run: |
          install.packages('remotes')
          install.packages("jsonlite", type="source")
          install.packages("usethis", type="source")
          install.packages("symengine", type="source")
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          install.packages('remotes')
          remotes::install_github("nlmixrdevelopment/dparser-R")
          remotes::install_cran("stringi")
          remotes::install_github("https://github.com/symengine/symengine.R")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("nlmixrdevelopment/lotri")
        shell: Rscript {0}

      - name: Test coverage
        run: |
           options(covr.flags = c(CFLAGS = "-O0 --coverage", CXXFLAGS = "-O0 --coverage", LDFLAGS = "--coverage"))
           pkgbuild::with_build_tools(covr::codecov(token="c1a47ffb-e5b5-420a-a0ed-6df480bcb833", quiet=FALSE))
        shell: Rscript {0}
