# NOTE: This workflow is overkill for most R packages
# check-standard.yaml is likely a better choice
# usethis::use_github_action("check-standard") will install it.
#
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-18.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest", http-user-agent: "R/4.1.0 (ubuntu-18.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
          - {os: ubuntu-18.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false

      - name: install libgit2-dev
        if: runner.os == 'Linux'
        run: sudo add-apt-repository ppa:cran/libgit2 && sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" && sudo apt-get update && sudo apt-get install libssh2-1-dev libgit2-dev libudunits2-dev  libgmp-dev libmpfr-dev libmpc-dev libharfbuzz-dev libfribidi-dev libicu-dev libicu55 -y
        shell: bash

      - name: Install X11 dependencies on MacOS
        if: runner.os == 'macOS'
        run: brew install --cask xquartz
        shell: bash

      - name: Install deps on MacOS
        if: runner.os == 'macOS'
        run: |
          brew install cairo
          brew install libgit2
          brew install udunits
        shell: bash

      - name: Link gfortran on MacOS
        if: runner.os == 'macOS'
        run: |
          sudo ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/gfortran-10 /usr/local/gfortran
        shell: bash

      - name: Create Makevars for Fortran linking options on macOS
        if: runner.os == 'macOS'
        run: |
          try(dir.create("~/.R"))
          writeLines(c("GCCBASE:=$(shell brew --prefix gcc)","FLIBS=-L$(GCCBASE)/lib/gcc/10/lib -lm",""),"~/.R/Makevars")
        shell: Rscript {0}

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "18.04"))')

      - name: Install remotes
        run: |
          install.packages('curl')
          install.packages('remotes')
          remotes::install_github("nlmixrdevelopment/dparser-R")
          remotes::install_cran("stringi")
          remotes::install_github("https://github.com/symengine/symengine.R")
        shell: Rscript {0}

      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          if (R.version$major < 4 && isTRUE(.Platform$OS.type == "windows")) {
            dotR <- file.path(Sys.getenv("HOME"), ".R")
            if (!file.exists(dotR)) dir.create(dotR)
            path_makevars <- ifelse(.Platform$OS.type == "windows", "Makevars.win", "Makevars")
            M <- file.path(dotR, path_makevars)
            if (!file.exists(M)) file.create(M)
            cat("\nCXX14FLAGS=-O3",
                "CXX14 = $(BINPREF)g++ -m$(WIN) -std=c++1y",
                "CXX11FLAGS=-O3",
                file = M, sep = "\n", append = TRUE)
          }
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
